using lucidRESUME.Core.Interfaces;
using lucidRESUME.Core.Models.Resume;
using lucidRESUME.JobML;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace lucidRESUME.Export;

/// <summary>
/// Exports a ResumeDocument to a professionally formatted PDF using QuestPDF.
/// Pure C#, cross-platform, no external tools.
/// </summary>
public sealed class PdfExporter : IResumeExporter
{
    static PdfExporter()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public ExportFormat Format => ExportFormat.Pdf;

    public Task<byte[]> ExportAsync(ResumeDocument resume, CancellationToken ct = default)
    {
        var template = ExportArtifact.Template(resume);
        var compact = ExportArtifact.CompactJobMl(resume);
        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(template.PageMarginPoints);
                // QuestPDF bundles Lato. Using it keeps PDF output deterministic on
                // clean machines and CI instead of depending on system fonts.
                page.DefaultTextStyle(x => x.FontSize(template.BodyFontSize).FontFamily("Lato"));

                page.Content().Element(c => ComposeContent(c, resume, template, compact));
            });
        })
        .WithMetadata(new DocumentMetadata
        {
            Language = "en-GB",
            Title = string.IsNullOrWhiteSpace(resume.TargetRole)
                ? $"{resume.Personal.FullName ?? "Candidate"} resume"
                : $"{resume.Personal.FullName ?? "Candidate"} - {resume.TargetRole}",
            Subject = "Evidence-linked resume generated by lucidRESUME",
            Author = resume.Personal.FullName ?? "lucidRESUME",
            Creator = "lucidRESUME"
        })
        .WithSettings(new DocumentSettings
        {
            PDFUA_Conformance = PDFUA_Conformance.PDFUA_1
        });

        var bytes = document.GeneratePdf();

        return Task.FromResult(bytes);
    }

    private static void ComposeIdentity(IContainer container, ResumeDocument resume, ResumeTemplate template)
    {
        var p = resume.Personal;
        container.SemanticSection().Column(col =>
        {
            if (p.FullName != null)
                col.Item().SemanticHeading1().Text(p.FullName).FontSize(22).Bold()
                    .FontColor($"#{template.AccentHex}");

            if (!string.IsNullOrWhiteSpace(p.Email))
                col.Item().SemanticParagraph().Text(p.Email).FontSize(8).FontColor(Colors.Grey.Medium);

            if (!string.IsNullOrWhiteSpace(p.Phone))
                col.Item().SemanticParagraph().Text(string.IsNullOrWhiteSpace(p.ContactPreference)
                        ? p.Phone
                        : $"{p.Phone} - {p.ContactPreference} -")
                    .FontSize(8).FontColor(Colors.Grey.Medium);
            if (!string.IsNullOrWhiteSpace(p.Location))
                col.Item().SemanticParagraph().Text(p.Location).FontSize(8).FontColor(Colors.Grey.Medium);

            var profiles = string.Join("  |  ", new[] { p.LinkedInUrl, p.GitHubUrl, p.WebsiteUrl }
                .Where(value => !string.IsNullOrWhiteSpace(value)));
            if (!string.IsNullOrWhiteSpace(profiles))
                col.Item().SemanticParagraph().Text(profiles).FontSize(8).FontColor(Colors.Grey.Medium);
            if (!string.IsNullOrWhiteSpace(resume.TargetRole))
                col.Item().SemanticParagraph().Text($"Target role: {resume.TargetRole}").FontSize(9).Bold()
                    .FontColor($"#{template.AccentHex}");

            col.Item().SemanticIgnore().PaddingTop(4).LineHorizontal(0.5f).LineColor(Colors.Grey.Lighten2);
        });
    }

    private static void ComposeContent(IContainer container, ResumeDocument resume, ResumeTemplate template,
        CJobMlProjection? compact)
    {
        container.PaddingTop(8).Column(col =>
        {
            col.Item().Element(c => ComposeIdentity(c, resume, template));
            col.Item().PaddingBottom(8);

            // Summary
            if (!string.IsNullOrWhiteSpace(resume.Personal.Summary))
            {
                col.Item().Element(c => SectionHeading(c, "Summary", template));
                CitedText(col.Item(), resume.Personal.Summary, compact, template, 9, 1.4f);
                col.Item().PaddingBottom(8);
            }

            // Skills near the top makes the human-facing pages easy to scan and
            // prevents a nearly empty skills-only second page.
            if (resume.Skills.Count > 0)
            {
                col.Item().Element(c => SectionHeading(c, "Skills", template));
                foreach (var g in resume.Skills.GroupBy(s => s.Category ?? "General"))
                {
                    var skills = string.Join(", ", g.Select(s => s.Name));
                    CitedText(col.Item(), $"{g.Key}: {skills}",
                        ExportArtifact.CitationNumbers($"{g.Key}: {skills}", compact), template, 8, 1);
                }
                col.Item().PaddingBottom(6);
            }

            if (resume.Projects.Count > 0)
            {
                for (var projectIndex = 0; projectIndex < resume.Projects.Count; projectIndex++)
                {
                    var proj = resume.Projects[projectIndex];
                    col.Item().ShowEntire().SemanticSection().Column(projectColumn =>
                    {
                        if (projectIndex == 0)
                            projectColumn.Item().Element(c => SectionHeading(c, "Selected Engineering", template));
                        projectColumn.Item().SemanticHeading3().Text(proj.Name).Bold().FontSize(9);
                        if (!string.IsNullOrWhiteSpace(proj.Description))
                            CitedText(projectColumn.Item(), proj.Description, compact, template, 8, 1.15f);
                        if (proj.Technologies.Count > 0)
                            projectColumn.Item().SemanticParagraph().Text(string.Join(", ", proj.Technologies))
                                .FontSize(8).Italic().FontColor($"#{template.AccentHex}");
                        projectColumn.Item().PaddingBottom(4);
                    });
                }
            }

            // Experience
            if (resume.Experience.Count > 0)
            {
                var secondPageExperienceIndex = ExportLayoutPolicy.SecondPageExperienceIndex(resume);
                if (secondPageExperienceIndex == 0)
                    col.Item().PageBreak();
                col.Item().Element(c => SectionHeading(c, "Experience", template));
                for (var experienceIndex = 0; experienceIndex < resume.Experience.Count; experienceIndex++)
                {
                    if (experienceIndex == secondPageExperienceIndex && experienceIndex > 0)
                        col.Item().PageBreak();
                    var exp = resume.Experience[experienceIndex];
                    if (exp.IsCompact && (experienceIndex == 0 || !resume.Experience[experienceIndex - 1].IsCompact))
                        col.Item().PaddingTop(5).SemanticHeading3()
                            .Text("Additional consulting, contract and earlier experience").Bold().FontSize(9);
                    col.Item().PaddingTop(experienceIndex == 0 ? 0 : exp.IsCompact ? 3 : 9)
                        .ShowEntire().SemanticSection().Column(experienceColumn =>
                    {
                        var dates = FormatDates(exp.StartDate, exp.EndDate, exp.IsCurrent);
                        var compactCitations = exp.IsCompact
                            ? ExportArtifact.CitationNumbers(exp.Achievements.FirstOrDefault() ?? string.Empty, compact)
                            : [];
                        experienceColumn.Item().SemanticHeading3().Row(header =>
                        {
                            header.RelativeItem().Text(text =>
                            {
                                if (!string.IsNullOrWhiteSpace(exp.Title))
                                    text.Span(exp.Title).Bold().FontSize(9);
                                if (!string.IsNullOrWhiteSpace(exp.Title) && !string.IsNullOrWhiteSpace(exp.Company))
                                    text.Span(" | ").FontSize(9);
                                if (!string.IsNullOrWhiteSpace(exp.Company))
                                    text.Span(exp.Company).Bold().FontSize(9).FontColor($"#{template.AccentHex}");
                                if (!string.IsNullOrWhiteSpace(exp.Location))
                                    text.Span($" | {exp.Location}").FontSize(8).FontColor(Colors.Grey.Medium);
                                for (var citationIndex = 0; citationIndex < compactCitations.Count; citationIndex++)
                                {
                                    var number = compactCitations[citationIndex];
                                    text.SectionLink(citationIndex == 0 ? $"\u00A0[{number}]" : $",\u00A0[{number}]",
                                            $"ref-{number}")
                                        .FontSize(8).FontColor($"#{template.AccentHex}").Underline();
                                }
                            });
                            if (!string.IsNullOrEmpty(dates))
                                header.ConstantItem(105).AlignRight().Text(dates).FontSize(8)
                                    .FontColor(Colors.Grey.Medium);
                        });

                        if (exp.Technologies.Count > 0)
                            experienceColumn.Item().SemanticParagraph().Text(string.Join(", ", exp.Technologies))
                                .FontSize(8).Italic().FontColor($"#{template.AccentHex}");

                        if (!exp.IsCompact && exp.Achievements.Count > 0)
                            experienceColumn.Item().SemanticList().Column(list =>
                            {
                                foreach (var achievement in exp.Achievements)
                                    list.Item().SemanticListItem().Row(row =>
                                    {
                                        row.ConstantItem(12).SemanticListLabel().Text("•").FontSize(8);
                                        CitedText(row.RelativeItem().SemanticListItemBody(), achievement,
                                            compact, template, 9, 1.3f, semanticParagraph: false);
                                    });
                            });

                        experienceColumn.Item().PaddingBottom(6);
                    });
                }
            }

            // Education
            if (resume.Education.Count > 0)
            {
                col.Item().Element(c => SectionHeading(c, "Education", template));
                foreach (var edu in resume.Education)
                {
                    var parts = new[] { edu.Degree, edu.FieldOfStudy, edu.Institution }
                        .Where(s => !string.IsNullOrWhiteSpace(s));
                    if (!string.IsNullOrWhiteSpace(edu.Institution))
                        col.Item().SemanticHeading3().Text(edu.Institution).Bold().FontSize(9)
                            .FontColor($"#{template.AccentHex}");
                    var qualification = string.IsNullOrWhiteSpace(edu.FieldOfStudy)
                        ? edu.Degree ?? ""
                        : $"{edu.Degree}, {edu.FieldOfStudy}";
                    if (!string.IsNullOrWhiteSpace(qualification))
                        CitedText(col.Item(), qualification,
                            ExportArtifact.EducationCitationNumbers(edu, compact),
                            template, 9, 1, bold: true);
                    var dates = FormatDates(edu.StartDate, edu.EndDate, false);
                    if (!string.IsNullOrEmpty(dates))
                        col.Item().SemanticParagraph().Text(dates).FontSize(8).FontColor(Colors.Grey.Medium);
                    col.Item().PaddingBottom(4);
                }
            }

            // Certifications
            if (resume.Certifications.Count > 0)
            {
                col.Item().Element(c => SectionHeading(c, "Certifications", template));
                foreach (var c in resume.Certifications)
                    col.Item().SemanticParagraph().Text($"{c.Name} - {c.Issuer}" +
                        (c.IssuedDate.HasValue ? $" ({c.IssuedDate.Value.Year})" : "")).FontSize(9);
                col.Item().PaddingBottom(6);
            }

            if (resume.Publications.Count > 0)
            {
                col.Item().SemanticSection().Column(publicationColumn =>
                {
                    publicationColumn.Item().Element(c => SectionHeading(c, "Selected Recent Publications", template));
                    publicationColumn.Item().SemanticParagraph().Text(text =>
                    {
                        for (var publicationIndex = 0;
                             publicationIndex < resume.Publications.Count;
                             publicationIndex++)
                        {
                            var publication = resume.Publications[publicationIndex];
                            if (publicationIndex > 0) text.Span(" · ").FontSize(8);
                            if (Uri.TryCreate(publication.Url, UriKind.Absolute, out var uri))
                                text.Hyperlink(publication.Name, uri.ToString()).FontSize(8)
                                    .FontColor($"#{template.AccentHex}").Underline();
                            else
                                text.Span(publication.Name).FontSize(8);
                        }
                    });
                    publicationColumn.Item().PaddingBottom(6);
                });
            }

            AppendReferences(col, compact, template);
        });
    }

    private static void SectionHeading(IContainer container, string title, ResumeTemplate template)
    {
        container.PaddingBottom(4).SemanticSection().Column(col =>
        {
            col.Item().SemanticHeading2().Text(title).FontSize(template.SectionFontSize).Bold()
                .FontColor($"#{template.AccentHex}");
            col.Item().SemanticIgnore().LineHorizontal(0.5f).LineColor($"#{template.AccentHex}");
        });
    }

    private static void CitedText(IContainer container, string text, CJobMlProjection? compact,
        ResumeTemplate template, float fontSize, float lineHeight, bool bold = false,
        bool semanticParagraph = true) =>
        CitedText(container, text, ExportArtifact.CitationNumbers(text, compact), template, fontSize, lineHeight,
            bold, semanticParagraph);

    private static void CitedText(IContainer container, string text, IReadOnlyList<int> numbers,
        ResumeTemplate template, float fontSize, float lineHeight, bool bold = false,
        bool semanticParagraph = true)
    {
        var textContainer = semanticParagraph ? container.SemanticParagraph() : container;
        textContainer.Text(descriptor =>
        {
            var prose = descriptor.Span(text).FontSize(fontSize).LineHeight(lineHeight);
            if (bold) prose.Bold();
            for (var index = 0; index < numbers.Count; index++)
            {
                var number = numbers[index];
                descriptor.SectionLink(index == 0 ? $"\u00A0[{number}]" : $",\u00A0[{number}]",
                        $"ref-{number}")
                    .FontSize(fontSize).LineHeight(lineHeight)
                    .FontColor($"#{template.AccentHex}").Underline();
            }
        });
    }

    private static void AppendReferences(ColumnDescriptor col, CJobMlProjection? compact, ResumeTemplate template)
    {
        if (compact is null || compact.References.Count == 0) return;

        col.Item().Element(c => SectionHeading(c, "References", template));
        col.Item().SemanticParagraph().Text(CJobMlProjector.SemanticPreamble)
            .FontSize(8).FontColor(Colors.Grey.Darken1);
        if (Uri.TryCreate(compact.FullJobMl, UriKind.Absolute, out var completeLedger))
            col.Item().SemanticParagraph().Hyperlink(completeLedger.ToString()).Text($"Full JobML: {completeLedger}")
                .FontSize(7).FontColor($"#{template.AccentHex}").Underline();

        foreach (var reference in compact.References)
        {
            var uriToken = string.IsNullOrWhiteSpace(reference.Evidence.Uri)
                ? null
                : $"<{reference.Evidence.Uri}>";
            var text = reference.PlainText;
            if (uriToken is not null)
                text = text.Replace(uriToken + ".", "", StringComparison.Ordinal).TrimEnd();
            col.Item().SemanticParagraph().Section($"ref-{reference.Number}").PaddingTop(3).Text(text).FontSize(7).LineHeight(1.15f)
                .FontColor(Colors.Grey.Darken2);
            if (Uri.TryCreate(reference.Evidence.Uri, UriKind.Absolute, out var uri))
                col.Item().SemanticParagraph().PaddingLeft(12).Hyperlink(uri.ToString()).Text(uri.ToString())
                    .FontSize(6.5f).FontColor($"#{template.AccentHex}").Underline();
        }
    }

    private static string FormatDates(DateOnly? start, DateOnly? end, bool isCurrent)
    {
        var s = start?.ToString("MMM yyyy") ?? "";
        var e = isCurrent ? "Present" : end?.ToString("MMM yyyy") ?? "";
        return s != "" || e != "" ? $"{s} - {e}" : "";
    }

}
